<?php 
if ($_GET){
	$data  = Mage::getModel('test/shivam')->load((int)$_GET['id']);
}
?>

<form action = "<?php echo Mage::getUrl('test/index/savemydata') ?>" method = "post">
	<table>
		<tr>
			<td>Name</td>
			<td>
				<input type = "text" name="name" value = "<?php echo $data->getName()?>"/>
			</td>
		</tr>
		<tr>
			<td>Address</td>
			<td>
				<input type = "text" name = "address" value = "<?php echo $data->getAddress()?>"/>
			</td>
		</tr>
		<tr>
			<td>Departments</td>
			<td>
				<input type = "text" name = "department" value = "<?php echo $data->getDepartment() ?>"/>
			</td>
		</tr>				
		<tr>
			<td>
				<input type = "hidden" name = "id" value = "<?php echo $data->getId()?>"/>
			</td>
		</tr>
		<tr>
			<td></td>
			<td>
				<input value = "Confirm Edit" type = "submit"/>	
			</td>
		</tr>						
	</table>
</form>